name: Actualización diaria de histórico

on:
  schedule:
    - cron: '5 13 * * 1-5'

env:
     RUN_ONCE: false


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      if: env.RUN_ONCE == false
      run: |
          python -m pip install --upgrade pip
          pip install build
          python -m pip install pandas
          pip install sqlalchemy-1.4.51
          pip install yfinance-latest
      env:
        RUN_ONCE: true

    - name: Ejecutar script diario 
      run: python ./data_engineers/actualizar_tabla_historico.py
