name: Actualización diaria de histórico

on:
  schedule:
    - cron: '0 0 * * 2-6'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          pip install sqlalchemy
          pip install psycopg2
          pip install yfinance
     

    - name: Ejecutar script diario 
      run: python ./data_engineers/actualizar_tabla_historico.py
